<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">

<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <title>Zend Framework Default Application</title>
    </head>
    <body>
        <div id="wrapper">
            <?php
            
            $date = "Monday";
            $month = "April";
            $time = "11:20:55";
            echo $this->t("Today is %1\$s in %2\$s. Actual time: %3\$s", $date, $month, $time);
            
            ?>
            
            <?php echo $this->t('Hello World!') ?>
        </div>
    </body>
</html>
